- name: app setup
  include_role:
    name: common
    tasks_from: app-setup

- name: nodejs setup
  include_role:
    name: common
    tasks_from: nodejs

- name: copy mongodb repo
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: install mongodb client
  ansible.builtin.dnf:
    name: mongodb-mongosh
    state: present

- name: check products loaded or not
  ansible.builtin.command: mongosh --host mongodb.gurulabs.xyz --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
  register: catalogue_output
  # ignore_errors: true
  # ignore_unreachable: true

- name: print catalogue output
  ansible.builtin.debug:
    msg: "{{ catalogue_output }}"
  # ignore_errors: true
  # ignore_unreachable: true

- name: load products
  ansible.builtin.shell: mongosh --host mongodb.gurulabs.xyz < /app/db/master-data.js
  when: catalogue_output.stdout | int < 0
  # ignore_errors: true
  # ignore_unreachable: true

- name: systemd setup
  include_role:
    name: common
    tasks_from: systemd.yaml

#error handling 
# 1- when: false [This will always skip the task.]
# 2- ignore_errors: true [The task is not ignored, it runs.If something inside deployment.yaml fails, Ansible just prints the error but continues.]
- name: Deployment when false error
  tags: 
    - deployment
  include_role:
    name: common
    tasks_from: deployment
  when: false #This will always skip the task.
# ansible-playbook -i inventory.ini main.yaml -e component=catalogue -e app_version=3 --tags=deployment

- name: Deployment ignore error true
  tags: 
    - deployment
  include_role:
    name: common
    tasks_from: deployment
  ignore_errors: true
